### ISSUE TITLE
matchdep will break when there is no package.json in the project

### ISSUE THREAD

**Issue by hvgeertruy** [tkellen/js-matchdep#11]
I stumbled on this one. You might want to create an error message for this as the current response is confusing.

```
$ grunt
Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'devDependencies' of null
>>     at /opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/matchdep/lib/matchdep.js:50:26
>>     at Array.forEach (native)
>>     at loadConfig (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/matchdep/lib/matchdep.js:49:9)
>>     at Object.matchdep.(anonymous function) [as filterDev] (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/matchdep/lib/matchdep.js:67:14)
>>     at Object.module.exports (/opt/apps/checkouts/experiments/node/webapp-new/client/Gruntfile.js:2:25)
>>     at loadTask (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/grunt/lib/grunt/task.js:318:10)
>>     at Task.task.init (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/grunt/lib/grunt/task.js:430:5)
>>     at Object.grunt.tasks (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/grunt/lib/grunt.js:113:8)
>>     at Object.module.exports [as cli] (/opt/apps/checkouts/experiments/node/webapp-new/client/node_modules/grunt/lib/grunt/cli.js:38:9)
>>     at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:43:20)

No tasks specified, running default tasks.
Running tasks: default
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

It makes sense when you know it, but it took me a while to figure out what was wrong.

The error specifies that it can not find grunt task "default" (but it was there!). If you dig deeper, you will notice this error:
```TypeError: Cannot read property 'devDependencies' of null```

turns out the script was missing this prop from package.json, but it failed to tell me it was missing package.json entirely.

I used *npm init* to fix this. Had to copy dependencies to devDependencies as well, otherwise grunt did not recognise my tasks.

**Comment by phated** [comment]
Published as 1.0.0
